name: santai
on: 
  push: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy to vps
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST}}
          username: ${{ secrets.VPS_USER}}
          key: ${{secrets.VPS_PRIVATE_KEY}}
          scripts: |
            cd ${{secrets.VPS_PATH}}
            git pull
